config:
  azure-native:location: westus3
  cst8918-a03-infra:appPath: ../
  cst8918-a03-infra:containerPort: '80'
  cst8918-a03-infra:publicPort: '80'
  cst8918-a03-infra:cpu: '1'
  cst8918-a03-infra:memory: '2'
  cst8918-a03-infra:prefixName: 'cst8918a03041269598'
  cst8918-a03-infra:imageTag: 'v0.3.0'
  cst8918-a03-infra:weatherApiKey:
    secure: AAABANfETAArqBfEuZ09cHJ+TCQUYf6S2HHPXcAUq5Ux3K9aQa4MwFjokdMv8F97MN72hEndk671rG3rmvMeYg==
